default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

user_config: &user_config
  username: postgres
  password: ''

development:
  <<: *default
  <<: *user_config
  database: upcase_dev

test:
  <<: *default
  <<: *user_config
  database: upcase_test

staging:
  <<: *default
  database: upcase_staging

production:
  <<: *default
  database: upcase_production
